# Generated by Django 4.2.6 on 2023-10-30 19:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("EmployeeApp", "0002_rename_employee_employees"),
    ]

    operations = [
        migrations.RenameField(
            model_name="departments",
            old_name="DeprartmentId",
            new_name="DepartmentId",
        ),
    ]
